#!/bin/sh

if [ "$1" = "--force-rebuild" ] || [ -z "$(docker image ls | grep pianoberry-build)" ]; then
  echo "Building pianoberry-build image"
  docker rmi $(docker images | grep 'pianoberry-build' | awk '{print $3}')
  docker build --no-cache -q -t pianoberry-build .
fi

mkdir -p deploy

docker run --privileged --rm -it -v ./deploy:/build pianoberry-build:latest
